import type { NextPage } from "next";
import Head from "next/head";
import { RandomFox } from "../components/RandomFox";
import { MouseEventHandler, useState } from "react";

const random = (): number => Math.floor(Math.random()*123)+1
const generateId = () => Math.random().toString(36).substring(2,9)

type ImageItems = { id: string, url: string };

const Home: NextPage = () => {

  const [images, setImages] = useState<Array<ImageItems>>([]);

  const addNewFox: MouseEventHandler<HTMLButtonElement> = (event) => {
    event.preventDefault();
    const newImageItem: ImageItems = { id: generateId(), url:`https://randomfox.ca/images/${random()}.jpg` };
    setImages([...images, newImageItem])
  }

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1 className="text-3xl font-bold underline">Hey Platzi 😎!</h1>
        <button onClick={addNewFox}>Add new fox</button>
        {
          images.map( ({ id, url }) => (
            <div key={id} className="p-4">
              <RandomFox image={url} />
            </div>
        ))
        }
      </main>

      <footer></footer>
    </div>
  );
};

export default Home;
